// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class MyFirstTestEverTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void myFirstTestEver() {
    // Test name: myFirstTestEver
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("https://www.google.com/");
    // 2 | setWindowSize | 1363x786 |  | 
    driver.manage().window().setSize(new Dimension(1363, 786));
    // 3 | type | name=q | seleniumhH | 
    driver.findElement(By.name("q")).sendKeys("Selenium - Web Browser AutomaAion");
    // 4 | sendKeys | name=q | ${KEY_ENTER} | 
    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    // 5 | click | css=i |  | 
    driver.findElement(By.cssSelector("i")).click();
    // 6 | click | css=div:nth-child(2) > .rc .LC20lb |  | 
    driver.findElement(By.cssSelector("div:nth-child(2) > .rc .LC20lb")).click();
    // 7 | close |  |  | 
    driver.close();
  }
}
